export const recentProjects = [
  {
    image: "/src/assets/images/gamevault.png",
    title: "Game vault",
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vitae nisi aperiam quia dolor vel pariatur?',
    stack: "html, css, js",
    responsive: true,
    preview: "https://game-vault-mu.vercel.app/",
    code: "https://github.com/MyaGwen/GameVault.git",
  },
  {
    image: "/src/assets/images/check it.png",
    title: "check it",
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vitae nisi aperiam quia dolor vel pariatur?',
    stack: "html, css, js",
    responsive: true,
    preview: "https://check-it-gamma.vercel.app/",
    code: "https://github.com/MyaGwen/Todo-list.git",
  },
  {
    image: "/src/assets/images/dog.png",
    title: "Man's BFF",
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vitae nisi aperiam quia dolor vel pariatur?',
    stack: "html, css, js",
    responsive: true,
    preview: "https://mans-bff-gallery.netlify.app/",
    code: "https://github.com/MyaGwen/Image-Gallery.git",
  },
  {
    image: "/src/assets/images/BB scoreboard.png",
    title: "Basketball Scoreboard",
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vitae nisi aperiam quia dolor vel pariatur?',
    stack: "html, css, js",
    responsive: true,
    preview: "https://tourmaline-selkie-6b5806.netlify.app/",
    code: "https://github.com/MyaGwen/Basket-Ball-ScoreBoard.git",
  },
  {
    image: "/src/assets/images/messi.png",
    title: "google search result of messi",
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vitae nisi aperiam quia dolor vel pariatur?',
    stack: "html, css",
    responsive: false,
    preview: "https://gilded-horse-a1a41a.netlify.app/",
    code: "https://github.com/MyaGwen/Stutern-Messi-google-search-result.git",
  },
  {
    image: "/src/assets/images/travel.png",
    title: "travel website",
    description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Vitae nisi aperiam quia dolor vel pariatur?',
    stack: "html, css",
    responsive: false,
    preview: "https://rainbow-clafoutis-d0bf85.netlify.app/",
    code: "https://github.com/MyaGwen/Travel-website.git",
  },
];
